plugins {
  id "com.vanniktech.maven.publish" version "0.34.0" // requires Java 11 for build
}

apply plugin: 'java-library'

group = 'org.pfsw'
version = '2.1.0'

ext {
  javaVersion = '8'
  javaModuleNameSuffix = 'julea-log4j2'
  autoModuleName = "${group}.${javaModuleNameSuffix}"
  libDisplayName = "PF JUnit Log Event Assertion (log4j2)"
  libDescription = "Library for asserting (log4j2) log events during junit testing"
  
  includePath = project.pfswGradleIncludePath // usually specified in $GRADLE_USER_HOME/gradle.properties
  repoUrlThirdParty = project.hasProperty('thirdPartyRepoUrl') ? project.getProperty('thirdPartyRepoUrl') : ''
  repoUrlReleases = project.hasProperty('pfswReleaseRepoUrl') ? project.getProperty('pfswReleaseRepoUrl') : ''
  ossrhUrlStaging = project.hasProperty('ossrhStagingRepoUrl') ? project.getProperty('ossrhStagingRepoUrl') : ''
  ossrhUrlSnapshots = project.hasProperty('ossrhSnapshotsRepoUrl') ? project.getProperty('ossrhSnapshotsRepoUrl') : ''
    
  nexusReleaseRepoUrl = repoUrlReleases
  nexusUsername = project.hasProperty('repo_user_name') ? project.getProperty('repo_user_name') : "master"
  nexusPassword = project.hasProperty('repo_user_password') ? project.getProperty('repo_user_password') : "desaster"

  localReleasePath = project.hasProperty('localReleasesDir') ? project.getProperty('localReleasesDir') : System.env['PF_RELEASES_REPO']
  
  sourceEncoding = project.hasProperty('source_encoding') ? project.getProperty('source_encoding') : 'UTF-8'
  islocalDevelopment = project.hasProperty('local_development') ? 'true'.equals(project.getProperty('local_development')) : false
  publishWithTests = false
  publishWithoutDependencies = false
  publishFixScopeCompile = true // not really relevant
  publishFixScopeProvided = true // not really relevant

  log4jVersion = '2.20.0'
  junit4Version = '4.13.2'
  junit5Version = '5.11.0'
	
	repositoriesClosure = {
	  if (islocalDevelopment)
	  {
	    mavenLocal()
	  }
	  if (localReleasePath)
	  {
	    maven {
	      name 'LocalRelease'
	      url localReleasePath
	    }
	  }
	  maven { 
	    url repoUrlThirdParty 
	  }
	}
}

archivesBaseName = "pf-${javaModuleNameSuffix}"

project.sourceCompatibility = project.ext.javaVersion
project.targetCompatibility = project.ext.javaVersion

tasks.withType(JavaCompile) {
  sourceCompatibility = project.ext.javaVersion
  targetCompatibility = project.ext.javaVersion
  options.release = Integer.valueOf(project.ext.javaVersion)
  options*.encoding = project.ext.sourceEncoding
  options.compilerArgs << "-Xlint:unchecked"
}

apply from: "${includePath}/java/publishing-java-full-maven-central.gradle"

dependencies {
  api group: group, name: 'pf-julea-core', version: '1.1.0'
  compileOnly group: 'junit', name: 'junit', version: junit4Version
  compileOnly group: 'org.junit.jupiter', name: 'junit-jupiter-api', version: junit5Version
  compileOnly group: 'org.apache.logging.log4j', name: 'log4j-core', version: log4jVersion
  
  testImplementation group: 'org.apache.logging.log4j', name: 'log4j-core', version: log4jVersion
  testImplementation group: 'org.apache.logging.log4j', name: 'log4j-slf4j-impl', version: log4jVersion
  testImplementation group: 'junit', name: 'junit', version: junit4Version
  testImplementation group: 'org.junit.jupiter', name: 'junit-jupiter-api', version: junit5Version
  testRuntimeOnly group: 'org.junit.jupiter', name: 'junit-jupiter-engine', version: junit5Version
  testRuntimeOnly group: 'org.junit.vintage', name: 'junit-vintage-engine', version: junit5Version
  testRuntimeOnly group: 'org.slf4j', name: 'slf4j-api', version: '1.7.36'
}

tasks.withType(Javadoc) {
  options.addStringOption('Xdoclint:none', '-quiet')
}

repositories repositoriesClosure

wrapper { gradleVersion = '8.11.1' }

println "${libDisplayName}: ${project.name} ${project.version} (moduleName:${autoModuleName}) ; Java ${javaVersion}"
println "Include path: ${pfswGradleIncludePath}"